In [28]:
import numpy as np

In [29]:
data=np.genfromtxt(r'C:\Users\girip\Downloads\DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',skip_header=True)

In [30]:
data

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [18]:
#task 1 score greater than 80

customer_spending_score_greater_than_80=data[data[:,3]>80]
spending_score_greater_than_80_count=customer_spending_score_greater_than_80.shape[0]
print("the customer who spend greater than 80:",customer_spending_score_greater_than_80)
print("the customer count who spend greater than 80:",spending_score_greater_than_80_count)

the customer who spend greater than 80: [[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]
the customer count who spend greater than 80: 30


In [23]:
#task 2 extract the customers who are 20 to 24 years of age

customers_between20_24=data[(data[:,1] >=20) &(data[:,1]<=24)]
print("Data of customers who are between 20 to 24 years of age:",customers_between20_24)

Data of customers who are between 20 to 24 years of age: [[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


In [24]:
#task 3 lowest and highest annual income

lowest_annual_income=np.min(data[:,2])
highest_annual_income=np.max(data[:,2])
print("lowest annual income $:",lowest_annual_income)
print("highest annual income $:",highest_annual_income)

lowest annual income $: 15.0
highest annual income $: 137.0


In [37]:
# task 4 customer age less than 45years and income>35k and score >75

customer=data[(data[:, 1] < 45) & (data[:, 2] > 35) & (data[:, 3] > 75)]
count=data[(data[:, 1] < 45) & (data[:, 2] > 35) & (data[:, 3] > 75)].shape[0]
print("Details of customers who are less than 45 years of age, have an annual income greater than $35K, and have a spending score greater than 75:",customer)
print("\nNumber of customers count:",count )

Details of customers who are less than 45 years of age, have an annual income greater than $35K, and have a spending score greater than 75: [[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]

Number of customers count: 26


In [38]:
#task 5 christmas season company wishes $10 to $50

gift_coupons = np.random.randint(10, 51, size=(data.shape[0], 1)) 
data_with_coupons = np.concatenate((data, gift_coupons), axis=1)
print("Details of customers after adding the new column for gift coupons:",data_with_coupons)

Details of customers after adding the new column for gift coupons: [[  1.  19.  15.  39.  38.]
 [  2.  21.  15.  81.  21.]
 [  3.  20.  16.   6.  25.]
 [  4.  23.  16.  77.  23.]
 [  5.  31.  17.  40.  22.]
 [  6.  22.  17.  76.  46.]
 [  7.  35.  18.   6.  40.]
 [  8.  23.  18.  94.  36.]
 [  9.  64.  19.   3.  38.]
 [ 10.  30.  19.  72.  30.]
 [ 11.  67.  19.  14.  33.]
 [ 12.  35.  19.  99.  37.]
 [ 13.  58.  20.  15.  43.]
 [ 14.  24.  20.  77.  14.]
 [ 15.  37.  20.  13.  37.]
 [ 16.  22.  20.  79.  47.]
 [ 17.  35.  21.  35.  32.]
 [ 18.  20.  21.  66.  17.]
 [ 19.  52.  23.  29.  36.]
 [ 20.  35.  23.  98.  36.]
 [ 21.  35.  24.  35.  23.]
 [ 22.  25.  24.  73.  15.]
 [ 23.  46.  25.   5.  10.]
 [ 24.  31.  25.  73.  25.]
 [ 25.  54.  28.  14.  18.]
 [ 26.  29.  28.  82.  26.]
 [ 27.  45.  28.  32.  38.]
 [ 28.  35.  28.  61.  14.]
 [ 29.  40.  29.  31.  10.]
 [ 30.  23.  29.  87.  13.]
 [ 31.  60.  30.   4.  39.]
 [ 32.  21.  30.  73.  28.]
 [ 33.  53.  33.   4.  44.]
 [ 34.  1